### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by ion201** [darko3/batch-renamer#1]
A few comments from glancing over your source:
- `#!/usr/bin/python`: You need to specify a python version. This won't point to Python 2 on all linux distros. 
- `--help\t\t\t\tprint`: Tab escape keys make your docstring harder to read. Just insert actual tabs or spaces instead. 
- `self.license_agree != "yes" or "y" or "n" or "no"`: This will always return True because `False or "y" == True`. The proper solution for is:
  
  ```
  any(self.license_agree in ('yes', 'y', 'no', 'n'))
  ```
- `os.mkdir("%s/.batch-renamer-cli" % home)`: It's poor form to dump your configuration/temp files in the current directory. (At least for linux) see:
  
  ```
  from gi.repository import GLib
  GLib.get_user_data_dir()
  GLib.get_user_cache_dir()
  GLib.get_user_config_dir()
  ```
- Enclosing your print statements in parenthesis will go a long way towards working with both python 2 and 3. 
- `print "Finished renaming %s files with a total time of %s seconds." % (self.file_counter, total_time)`: Neither of these variables are strings, you should use the appropriate formatting flags %d and %f. 
- `end = time.time()`: On windows, time.clock() is much more accurate. (On linux time.clock() is straight up wrong though).
- `enter_to_continue = raw_input(...`: this should be split into lines at each `\n` for readability. 
- `sys.exit(0)`: An exit status of 0 means success. You should be exiting with a non-zero status for errors. 
- The MIT license doesn't permit the notice to be removed but you've made it an integral active part of the program. It should be reproduced in a comment at the top of the file. This will make it easier for others to modify your code without violating your license. 
- `class Main():`: you aren't using this as a class, so it doesn't need to be a class. This would suffice:
  
  ```
  def main():
          myName = 'hello world'
      def rename():
          RENAME_FUNCTION(myName)
  ```

Or even better, get rid of the global variables:

```
def rename(old_name, new_name):
    # ...
def main():
    myName = 'hello wrold'
    rename(myName, 'hello world')
```

In general, passing values as function arguments is better than relying on a single variable to hold all your parameters.
- `elif self.license_agree == "yes":` replace that `elif` with a simple `if` and you no longer need to duplicate code in the preceding if statement. 
- `for file in files:` in python 2, `file` is a preexisting type variable.
- A try block should encompass as little code as possible. Reduce your `try: ... except OSError` to only the lines that can produce that error. Also, this can be an important error when renaming files, make it known to the user when this error is raised unless you specifically expect it in a particular place.

**Comment by darko3** [comment]
Thanks a lot for these tips man, I will try to improve my code with these whenever I have time!

**Comment by darko3** [comment]
@ion201 I updated the source code, is everything okay now or is there anything else I need to change?

**Comment by ion201** [comment]
Instead of nested try blocks, you can do this:

```
try:
    # Some code
except NameError:
    # Do something
except KeyboardInterrupt:
    # Do something else
```

Try to avoid using `sys.exit(0)` as the "default" exit after a successful run. A script with well-designed flow will always exit at the end of the file when successful.

Travis-ci is normally used with a unit testing tool like pytest. Just something to keep in mind - there doesn't seem to be much suited to unit testing here.

Overall, your conventions and flow are much better. Maybe some minor design changes to be made for flexibility or extensibility, but it'll come to you with practice :)

**Comment by darko3** [comment]
@ion201 Thanks a lot for all your help!
